# Generated by Django 2.2.8 on 2019-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('rss_url', models.URLField()),
                ('date_format', models.CharField(max_length=255)),
            ],
        ),
    ]
