# Generated by Django 2.2.9 on 2019-12-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20191216_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, help_text='Enter tags for search using whitespaces between', max_length=255),
        ),
    ]
