# Generated by Django 3.0.4 on 2020-06-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191219_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('publisher',), 'verbose_name': 'Джерело новин', 'verbose_name_plural': 'Джерела новин'},
        ),
    ]
