# Generated by Django 3.0.4 on 2020-04-14 16:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='дата створення')),
                ('direction', models.CharField(choices=[('0', "в'їзд"), ('1', 'виїзд')], default=0, max_length=10, null=True, verbose_name='напрям переміщення')),
                ('departure', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='країна відправлення')),
                ('arrival', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='країна призначення')),
                ('kids_number', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='кількість')),
                ('accamp_number', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='кількість')),
                ('nonaccamp_number', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='кількість')),
                ('cargo_number', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='кількість')),
                ('purpose', models.CharField(choices=[('0', 'тимчасове ввезення'), ('1', 'транзит'), ('2', 'зворотне вивезення')], default=0, max_length=10, null=True, verbose_name='мета переміщення')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doc', to='user.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='auto', to='user.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.TextField(blank=True, null=True, verbose_name='найменування товару')),
                ('goods_number', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='кількість')),
                ('goods_unit', models.CharField(choices=[('0', 'кг'), ('1', 'л'), ('2', 'шт')], default=0, max_length=10, null=True, verbose_name='одиниця виміру')),
                ('goods_value', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='вартість')),
                ('goods_currency', models.CharField(choices=[('0', 'грн.'), ('1', 'євро')], default=0, max_length=10, null=True, verbose_name='валюта')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='declaring.Entry')),
            ],
        ),
    ]
