# Generated by Django 3.0.4 on 2020-04-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='найменування товару'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_unit',
            field=models.CharField(choices=[('0', 'кг'), ('1', 'л'), ('2', 'шт')], default=0, max_length=10, null=True, verbose_name='одиниця'),
        ),
    ]
