# Generated by Django 3.0.4 on 2020-04-21 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaring', '0003_auto_20200421_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='accamp_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='кількість'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='cargo_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='кількість'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='direction',
            field=models.CharField(choices=[('0', "в'їзд"), ('1', 'виїзд')], default=None, max_length=10, null=True, verbose_name='напрям переміщення'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='kids_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='кількість'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='nonaccamp_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='кількість'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='purpose',
            field=models.CharField(choices=[('0', 'тимчасове ввезення'), ('1', 'транзит'), ('2', 'зворотне вивезення')], default=None, max_length=10, null=True, verbose_name='мета переміщення'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_currency',
            field=models.CharField(blank=True, choices=[('0', 'грн.'), ('1', 'євро')], default=None, max_length=10, null=True, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='найменування'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='кількість'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_unit',
            field=models.CharField(blank=True, choices=[('0', 'кг'), ('1', 'л'), ('2', 'шт')], default=None, max_length=10, null=True, verbose_name='одиниця'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='вартість'),
        ),
    ]
