# Generated by Django 3.0.4 on 2020-04-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaring', '0004_auto_20200421_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='limited',
            field=models.CharField(choices=[('0', 'ні'), ('1', 'так')], default=None, max_length=10, null=True),
        ),
    ]
