# Generated by Django 3.0.4 on 2020-04-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaring', '0005_entry_limited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='limited',
            field=models.CharField(choices=[('1', 'так'), ('0', 'ні')], default=None, max_length=10, null=True),
        ),
    ]
