# Generated by Django 3.0.4 on 2020-04-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaring', '0006_auto_20200421_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='purpose',
            field=models.CharField(blank=True, choices=[('0', 'тимчасове ввезення'), ('1', 'транзит'), ('2', 'зворотне вивезення')], default=None, max_length=10, null=True, verbose_name='мета переміщення'),
        ),
    ]
