# Generated by Django 3.0.4 on 2020-06-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declaring', '0008_auto_20200429_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-update_date',), 'verbose_name': 'Декларація', 'verbose_name_plural': 'Декларації'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('-entry',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
    ]
