# Generated by Django 3.0.4 on 2020-06-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorderPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('tag', models.CharField(max_length=3)),
                ('ukr', models.CharField(max_length=500)),
                ('eng', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('index', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
    ]
