# Generated by Django 3.0.4 on 2020-04-03 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='назва')),
                ('doc_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='номер')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
    ]
