# Generated by Django 3.0.4 on 2020-04-05 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_date',
            field=models.DateField(null=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(max_length=250, null=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_number',
            field=models.CharField(max_length=250, null=True, verbose_name='номер'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_name', models.CharField(max_length=250, null=True, verbose_name='марка')),
                ('auto_year', models.PositiveIntegerField(default=2020, null=True, validators=[django.core.validators.MinValueValidator(1950), user.models.max_value_current_year], verbose_name='рік випуску')),
                ('auto_engine', models.PositiveIntegerField(default=1600, max_length=4, null=True, verbose_name="об'єм двигуна")),
                ('auto_vin', models.CharField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='кузов №')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транспортний засіб',
                'verbose_name_plural': 'Транспортні засоби',
            },
        ),
    ]
